name: bilibili_music
description: 一个简洁、功能齐全的B站视频音频提取播放器
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  go_router: ^12.1.1
  dio: ^5.8.0+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.10
  just_audio_windows: ^0.2.2
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  flutter_vector_icons: ^2.0.0
  lottie: ^2.7.0
  path_provider_windows: ^2.3.0
  shared_preferences_windows: ^2.4.1
  crypto: ^3.0.6
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.10.0
  audio_service: ^0.18.12
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.1.2
  path: ^1.8.3
  url_launcher: ^6.3.1
  intl: ^0.18.1
  window_manager: ^0.3.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.9
  flutter_easyloading: ^3.0.5
  animations: ^2.0.8
  permission_handler: 10.4.5
  fftea: ^1.5.0
  qr_flutter: ^4.1.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  http: ^0.13.6
  tray_manager: ^0.2.0
  audio_session: ^0.1.25
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  flutter_media_metadata: ^1.0.0+1
  flutter_downloader: ^1.11.5
  flutter_local_notifications: ^15.1.0+1
  system_tray: ^2.0.3
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  injectable_generator: ^2.2.3
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/app_icon.ico
    - assets/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "bilibili-icon-lg.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "bilibili-icon-lg.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "bilibili-icon-lg.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "bilibili-icon-lg.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "bilibili-icon-lg.png"