name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Setup keychain
      run: |
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings build.keychain
        security list-keychains -d user -s build.keychain

    - name: Build iOS app
      run: |
        flutter build ios --no-codesign --release --no-pub

    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r Runner.ipa Payload
        cd ../../../

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: build/ios/iphoneos/Runner.ipa

    - name: Cleanup keychain
      if: always()
      run: |
        security delete-keychain build.keychain 