name: Build iOS IPA

on:
  push:
    branches:
      - main  # 触发构建的分支
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # 指定 Flutter 版本
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign  # 构建未签名的 iOS 应用

      - name: Create IPA
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r9 Runner.ipa Payload  # 打包成 IPA 文件

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: Runner.ipa
